### ISSUE TITLE
Performance slowed down when typing

### ISSUE THREAD

**Issue by Noitidart** [Quicksaver/FindBar-Tweak#122]
Hi there,
I'm using this addon and I like it a lot however I'm having performance issues, I can live with it but if it can be fixed it would be superb. When I type in a textarea or anything it slows down the input, letters i typed show up with like a 200ms delay.

My computer is from 2004 so I notice performance issues, I like it though it helps me make good perfromance stuff and help others with their performance.

**Comment by Quicksaver** [comment]
Please try the latest beta version 2b2 which I just uploaded (in the Development Channel section near the bottom at https://addons.mozilla.org/en-US/firefox/addon/findbar-tweak/) and reopen the issue if you still experience any performance problems. The latest beta has many (many!) improvements that should increase performance and stability overall, so hopefully your experience with the add-on will be better, even in editable nodes like in your case.

**Comment by Noitidart** [comment]
Will test now thanks!

**Comment by Noitidart** [comment]
This is unrelated to the lag when typing. But when it does the find in all tabs it lags the whole browser for a few sec :( But its a worth it trade off, as long as the typing lag isnt there. Although it would be awesome if we could get rid of that lag too, is it possible to do it from worker threads?

**Comment by Quicksaver** [comment]
Is that when the FIAT window opens or when you run a search in it? I actually don't see any lag like that, not even in fairly long pages... Could you maybe try to find a specific example of a webpage and what to find for and such?

The find mechanism in FIAT is already fully asynchronous, and it has a sort of pause/sleep system that makes it search in chunks basically, precisely to prevent the browser from locking up like that. It's very strange that it still does lock up for you... Does the same happen when you highlight a page? It has a similar in-chunks mechanism.

**Comment by Noitidart** [comment]
Thanks @Quicksaver this is an addon i badly wanted to use. After you told me the typing was fixed i tried it out and you are absolutely right i didn't notice any typing issues. However now overall perforamnce is slowed and I had to disable :( I really badly need a lightweight thing that find in all tabs as i have lots of documentation open. Maybe you could make a very simple light weight version please?

I really badly need that feature.

Especially when it would do the finding in all tabs it would lock my browser real hard :(

**Comment by Quicksaver** [comment]
Hmm, in theory at least, Find in All Tabs should perform better now in fact, unless of course I screwed up somewhere. I'll do some testing with lots of tabs open (give me a normal number for you, 50? More?) and see if I can figure something out.

I didn't fully understand if you meant it's only Find in All Tabs that's slower or everything about the find bar in general.

**Comment by Noitidart** [comment]
I have teamviewer so if you would like i can let you connect. ill also try to take a video. I have a 14 tab groups. 10 of them have a bunch of inactive tabs as i havent loaded them yet. the 4 groups im using right now, first one has 44 tabs, 2nd one has 13, 3rd has 6, and 4th has 25. A lot of these tabs are of documentation on various api's so find in all tabs is a god send but its slowing perf till crash it might not be you though thanks so much for trying to fix it. it could be leaky addons i have installed

**Comment by Quicksaver** [comment]
Well as a starting point, if you could test it with all those tabs without any other add-ons installed, it would be great!

But I will still do some testing like that as well, as I have to admit I haven't gotten to testing a big number of tabs like that yet.

**Comment by Noitidart** [comment]
Thanks I'll take a youtube screencast and post for you on how it locks up :) just a bit busy these couple of days :(

**Comment by Quicksaver** [comment]
You're absolutely right, I did some testing with a heavier set of tabs open and it would lock up for a couple of seconds for me as well.

I just uploaded beta version 2b3 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b3) with what I think is a very big improvement in performance for the find in all tabs dialog.

In short, it's a mixture of the current (v2) code with what it was before (v1.4.x). Instead of starting all the processing "almost at once" like it was doing, it "waits" until the current tab has finished processing before moving to the next one, but it allows room for some asynchronous overlap so it's not exactly sequential either. It seems to be a good compromise for taking advantage of your full processing power without overloading it.

Perhaps it will take a little bit longer to finish processing all the tabs in cases with lots of tabs open, but it shouldn't lock up the window as it runs, so you can start inspecting the results as they come in.

I tested with 78 tabs open, many of them pretty big with thousands of results each. It takes about 4-5 seconds to process them all, and while it's running it can be a little jumpy when processing the biggest tabs (~4000 results), but I can use the lists without a problem as the results show up, even while processing those biggest tabs.

If you could give 2b3 a try and let me know what you think I'd appreciate it.

**Comment by Noitidart** [comment]
Thank you very much @Quicksaver  man your multi tab search feature is so criticial I will test it out right away :)

**Comment by Noitidart** [comment]
Hey @Quicksaver things look pretty smooth now I think. I need to test more.

One thing though is if I do a find when highlight all is selected, then i close the find bar, all the instances remain highlighted, is that by design?

**Comment by Quicksaver** [comment]
Yeah, you need to enable "Remove highlights when the findbar is closed" in the preferences to change that.

**Comment by Noitidart** [comment]
Thanks for the quick reply! That was always so annoying haha thanks for letting me know about that.

**Comment by Quicksaver** [comment]
No problem. :)

**Comment by Noitidart** [comment]
Holy hell I just opened the options page and gosh dang man its beautiful!

**Comment by Noitidart** [comment]
You gotta add some search feature to the options thing man theres so much in here, wow beautiful

**Comment by Quicksaver** [comment]
I'm glad you like it, but I can't take all the credit, since I based it on firefox's new options tab.

And that's a good idea, I'll try to add some kind of search ability in there when I work on the import/export settings part. Shouldn't be too hard. Thanks for the suggestion!

**Comment by Noitidart** [comment]
Oh wow I loooove how the option for close findbar when loses focus, doesnt lose focus as I scroll! That option with remove all highlights on findbar close is beautiful!

**Comment by Quicksaver** [comment]
You seem to be having fun exploring the add-on. :)

**Comment by Noitidart** [comment]
Haha yeah man I never got past the find in all tabs thing because thats what I really used it for. And I would never get past exploring that as I would struggle to get perf right on that as I thought it was on my side. 

So finally thats smooth I went deeper in and wow fixes for small annoyances in FindBar behavior of firefox were found in here too.

There are some unrelated things to findbar expeirence like double clicking selects space after word etc. So thats kind of out of place maybe its own addon.

But overall A+!

**Comment by Noitidart** [comment]
I also like how you bring a GUI to the quick findbar prefs, there is no GUI for that. I can't recall but there was this beutiful support.mozilla page that outlined all of the prefs, just wanted to check if everything there was covered in here :)

**Comment by Quicksaver** [comment]
> There are some unrelated things to findbar expeirence like double clicking selects space after word etc. So thats kind of out of place maybe its own addon.

That's true, there are some more general things in there like that double clicking option. I included it because someone asked me to as a shortcut some time ago, since it does affect the findbar. I still need to add a notice in there to remind everyone that affects the browser globally, not just the findbar.

> I also like how you bring a GUI to the quick findbar prefs, there is no GUI for that. I can't recall but there was this beutiful support.mozilla page that outlined all of the prefs, just wanted to check if everything there was covered in here

Probably not, but I think at least the most useful preferences are in there. (Except for links-only, which currently you need to use the " ' " keyboard key to access this mode, and I already plan on improving this, but that's a whole other thing.) But if you think there's something there missing that should be there, let me know!

> But overall A+!

Thanks! Coming from a felow coder, that means a lot! :)

**Comment by Quicksaver** [comment]
> I think its missing the quick find starter key for "links only" or "all text" like if you / first then it searches links only etc.

I already plan to add these as sort of "Find modes" to the actual find bar, kind of like how there's a "Match case" mode, but for "Links Only", "No Input Boxes", etc.
