### ISSUE TITLE
Pale Moon

### ISSUE THREAD

**Issue by robmadden1** [Quicksaver/FindBar-Tweak#161]
Can you please make this compatible with Pale Moon v25 it dont work with it anymore with the new version.

**Comment by CuloArdido** [comment]
>but to say firefox looks like chrome is just wrong

In fact he was right and this is something that has been accentuated more and more in the last versions (especially with WebExtensions).
Maybe you're no longer interested, but what do you think about continuing to develop the extension exclusively for Palemoon (or some other Firefox fork that isn't a mediocre copy of Chrome)? [FinderBar Tweak](http://addons.palemoon.org/addon/finderbar-tweak/) could use a hand because is locked in Palemoon 27 due to [this bug](https://forum.palemoon.org/viewtopic.php?f=46&t=15854).
And Ghost, you shouldn't have deleted your other posts since it's not entirely clear what you were discussing with QuickSaver.
