### ISSUE TITLE
Multiple bugs with FindBar results displayed and highlighting

### ISSUE THREAD

**Issue by liftir** [Quicksaver/FindBar-Tweak#193]
1. Go to https://addons.mozilla.org/en-US/firefox/
2.  Press ctrl+F to bring up FindBar Tweak and search for "add-ons".
3. FindBar shows 1 of 7 matches, even though there are only 4 matches visible and highlighted.  They are labeled #1, #2, #3, #4 in red text shown in the included screenshot.
4. Match 1 of 7, Label #1, should be highlighted green as it is the current hit (see FindBar showing 1 of 7 matches) but It is highlighted purple.  If you click "Find next occurrence" it will take you to the result that's labeled #2 and Findbar with show "2 of 7 matches".  Occurrence #2 will be highlighted green as expected since #2 is now the current hit.  Now if you click "Find previous occurrence" it will go back to  #1 and highlight it green as the current hit.  So something is wonky with highlighting current hit and first occurrence on the first time searching through a page.
4.  If you press F3 to scroll through all matches, the Sights Style Circle animation will trigger properly on the 4 visible results.  But it also triggers 2 more times, seemingly on nothing visible.

![Screenshot](https://cloud.githubusercontent.com/assets/6834608/7899890/f0e35f70-0704-11e5-8098-8f025dd399a6.png)

**Comment by Quicksaver** [comment]
I can't reproduce the issue with the first result not being green (focused) in my local build, but I did tweak that in the meantime, so it's probable that I fixed it without knowing. I'll be uploading the next version soon, so when the add-on updates let me know if you still experience this.

As for the matches that are apparently not visible, that's mozilla's website trickery; try mousing over those add-ons at the bottom to read their full description and you'll see the hidden text there which contains the word "add-ons". ;) Same thing will happen if you search for a word that exists in one of those top panels that scrolls sideways (in your screenshot you have visible "First time with add-ons", but there are panels to the left and the right of that.

The thing is, that text does exist in the webpage, so the add-on (actually it's firefox itself that actually finds the results, the add-on just uses the matches that firefox finds, but that's besides the point) accounts for those. This is one of the things that I plan to improve, to somehow let you know that those results are there but only they're invisible, and you need to do "something" to make them visible; but it's not like the add-on can make them visible automatically because every website has its own kind of trickery (there are literally thousands of ways to accomplish this effect).

I have no idea how or when I will be able to do this though, as it's much easier said than done. Just wanted to let you know that in 99.9% of the cases, if the findbar finds something, it's there, you just have to look for it. ;)
