### ISSUE TITLE
Findbar closes after using video fullscreen

### ISSUE THREAD

**Issue by gotquestions** [Quicksaver/FindBar-Tweak#196]
I have the findbar set to open at startup and always stay open and when I open a video to fullscreen then close fullscreen, the findbar is no longer showing.
Please fix. Windows Vista firefox 38 
I am using Findbar Tweak 2b1 now as the latest seems to not be completed and ready to try.
Thankyou

**Comment by Quicksaver** [comment]
That's actually default Firefox behavior, it closes the findbar when entering full screen mode. But you're right of course, if the findbar was visible before entering fullscreen, it should still be visible after exiting fullscreen. I quickly fixed it and uploaded beta version 2b7 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b7) for you to try, let me know if you have any problems with it.

**Comment by gotquestions** [comment]
Thankyou for response.

That version V2b7is so completely unusable for me. So many things wrong with it. The findbar closed so I checked to see if options needed resetting and there is no options for me. I click Options and I get to this page:
about:findbartweak
How can I get to Options?

Findbar still closes after open/close Video Fullscreen.
I Ctrl+F and findbar opens but then it disappears with Tab change.
NO animated highlight.
NO number of matches.

**Comment by Quicksaver** [comment]
Have you restarted firefox after installing it? I remember 2b1 had some issues with disabling, so it might not have updated properly.

**Comment by gotquestions** [comment]
Okay I did a firefox restart and the findbar is still showing after open/close video fullscreen.
Thankyou for that.

I have to open the findbar for each tab, it will remain if I switch tabs but only if I initially Ctrl+F for each tab.
And the other issues still remain.
I see the term on the page and click Next/Previous but nothing happens.
Highlight was initially on and no terms were highlighted and Next/Previous did not function.
I clicked highlight off, then on again and all terms highlight but no change when then click Next/Previous.
Each page has it's own findbar term. When I change the term on one page, then switch tabs to  another page the term is still set at the last previous term. I expected the findbar term to change for all pages.
![2015-06-18_09-15-36](https://cloud.githubusercontent.com/assets/8550969/8236207/b940861a-159b-11e5-932f-91ddf19c6988.gif)

**Comment by Quicksaver** [comment]
It's likely a conflict with another add-on, in particular with whatever is giving your findbar that look and those extra buttons. Please try disabling all your other add-ons and see if FBT works correctly then. Also, what firefox version are you using?

**Comment by Quicksaver** [comment]
And the preference for the global findbar has changed and you'll have to re-enable it if you haven't already. It is now (more appropriately) called "Use a single global findbar for all tabs"

**Comment by gotquestions** [comment]
I stated in my first post that am firefox 38. 
Had to go back to version 2b1 and now my additional toolbars will open fine again.
It was Stylish Custom that caused the problem and need to keep it.
But I still can't get to options to change preferences. I click options and it takes me to about:findbartweak
Thanks

**Comment by Quicksaver** [comment]
> I stated in my first post that am firefox 38. 

Yes you did, I'm sorry about that.

> It was Stylish Custom that caused the problem and need to keep it.

Here's the problem with Stylish Custom, it's **severely** outdated. I don't think it's being actively worked on anymore by anyone, and you lose many things that Stylish 2 and the most recent versions of firefox introduced (I only noticed that you lose CSS syntax highlighting at least, and that was in the first 10 seconds of using SC).

Also this is not something I can fix from within FBT, because SC completely overrides many of FBT's modifications to the findbar; I had already asked its developer a long time ago to change that method and he did at the time, but he must have changed it back in the meantime because of the clear button apparently.

It's that clear button, the way it's implemented it completely destroys FBT. If you really need SC (and I advise you to find alternatives if you really need anything from it, honestly), then you can modify its code to work with FBT.

I assume you're using v1.5.1g found here. Find your SC add-on files in your profile folder. You'll have to modify file Stylish-Custom@srazzano.com/skin/overlay.css, and remove the following bit in line 15:
```CSS
findbar { 
  -moz-binding: url("chrome://stylish-custom/content/clear.xml#clear"); 
}
 ```
> But I still couldn't get to options to change preferences. I click options and it takes me to about:findbartweak

That address is the new preferences tab for the add-on. Do you mean you can't access it with SC disabled?

**Comment by Quicksaver** [comment]
BTW you'll also be unable to use SC at all with Firefox 41 (or around there) because SC is not signed, and since it's not on AMO (except for an even older version) it won't be signed.

**Comment by gotquestions** [comment]
Actually SC 1.5.1a
Yes when SC is disabled.
I am directed to about:findbartweak BUT NOW I see that I have to click the General Tab and I get to OPTIONS about:findbartweak#general
It should automatically have gone to General Tab on first run.

Will try later your workaround "remove the following bit in line 15"
Thanks!
Firefox 41? So upset. I was aware of it coming from reading the thread. Not sure what I will do. 
Holding out for as long as I can.
Thanks much
