### ISSUE TITLE
Match case on by default

### ISSUE THREAD

**Issue by kcamnairb** [Quicksaver/FindBar-Tweak#203]
Whenever I open my find bar on a new tab, the "Match case" button is selected. I usually do not want this option so I constantly have to unselect it. This only happens on my work computer for some reason.

**Comment by Quicksaver** [comment]
Please try the latest version 2, you can find it at the top of https://addons.mozilla.org/firefox/addon/findbar-tweak/versions/

If that doesn't help, that's likely a problem caused by another add-on (even one you might not have installed anymore), that might have changed the config option and not reverted it back. You'll have to go to the configuration page (type "about:config" in the location bar), look for "accessibility.typeaheadfind.casesensitive" and change it's value to 0 (zero, the number).

Please let me know if none of that helps.

**Comment by kcamnairb** [comment]
I changed "accessibility.typeaheadfind.casesensitive" to 0 and it fixed the problem.  Thanks a lot.

**Comment by hmijail** [comment]
I also was having this pain-in-the-neck problem - thanks for the solution. 
If you know what is / are the "guilty" add-ons, that might be useful!

**Comment by Quicksaver** [comment]
Unfortunately I have no idea. Technically speaking it could even be FBT itself, since it does use it obviously, but every time this comes up I can never figure out exactly how it could even cause it to behave this way. :(
