### ISSUE TITLE
Show "find in all tabs" in the main window

### ISSUE THREAD

**Issue by thenoncoder** [Quicksaver/FindBar-Tweak#206]
the old *find in all tabs* used to be directly inside the findbar, and not as a pop-up window, and in my opinion, it was better that way. Maybe you could like add an option to allow us to either enable or disable that?

**Comment by Quicksaver** [comment]
The plan is to re-add this ability as a sidebar with all the results for all open tabs, which will be much more easy and intuitive to use, with many more options than before.

**Comment by thenoncoder** [comment]
That's awesome! Thanks dude! :)

**Comment by Quicksaver** [comment]
There were several problems with the old model, not only did it take an excessive amount of screen space and didn't even take full advantage of all that space, it was also very difficult to maintain, especially considering the new features I am still planning for it (which will come later). I'm sorry to say I have no plans to bring back that exact design, but I can guarantee you will feel much more at ease with the planned new design.

**Comment by thenoncoder** [comment]
Bro, listen. I was saying that, you should include an option to switch between the two designs.
Maybe then also you can make the new one the default one for new users, if you want!

**Comment by Quicksaver** [comment]
If I were to include the previous design, I would have to maintain it and keep it working (I sure am not going to include something and then have it broken later, I would always have to fix it and include all the new options I want to add into it).

It is a flawed design for which the very little benefit it brings would simply not be worth the far too much effort it would take to maintain it.

**Comment by thenoncoder** [comment]
Bro, listen, this isn't a phone screen here, so there is no issue of *the findbar taking up the whole screen* or any stuff like that. Nothing *flawed* bro!

**Comment by Julian-Lin** [comment]
1. May I know when will a beta version to "show "find in all tabs" in the main window" even in sidebar? The main page get focus after clicking on one of the search result. Users can not navigate through the found list conveniently as prior version. 
2. Would you please have an option to have the found list of "find in all tabs" get focus when search, such that users can just use up/down arrow key to quickly navigate the found words in the web page without any mouse operations.

**Comment by Quicksaver** [comment]
> there is no issue of the findbar taking up the whole screen or any stuff like that

Actually it is, but that's not the only issue it had. I don't think you'll convince me of this, especially not before I write the new design.

> May I know when will a beta version to "show "find in all tabs" in the main window" even in sidebar?

This is the very next feature I will work on, so hopefully it won't be too long. But unfortunately I don't have an exact release date to give you.

>  The main page get focus after clicking on one of the search result. Users can not navigate through the found list conveniently as prior version. 

This is very true, I'm already trying to figure out a way to allow a better keyboard navigation, it's something like what you suggested in point 2. In the meantime, mouse navigation should be just fine (scrolling with the middle mouse button and clicking the scrollbar), so you'll have to use it for now. I know this is far from the best choice for you, but I assure you it's only temporary.

**Comment by Quicksaver** [comment]
@Julian-Lin please give beta version 2.0.2b1 a try (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.2b1). The biggest change in it is: to go to a match you have to press enter or double-click an entry from the Find in All Tabs lists; single-clicking the exact (highlighted) match in the lists is still possible.

Hopefully that should make the Find in All Tabs standalone window at least usable for your case, until I write the new version.

**Comment by Julian-Lin** [comment]
Thank you for the quick response and effort. However, I still would like to have "find in all tabs" in the main window, rather than a standalone window. Such that, I can see both web page and "find in all tabs" and navigate them with up/down arrow key at the same time. Dobule-clicking or pressing enter are redundant operations compared with previous versions. In fact, I prefer the old model as @thenoncoder suggested. If the "sidebar" is a must, would you please have it in the bottom of the window as the original find bar. If the sidebar is at left or right, it will impact the layout/appearance of the web page and users need to scroll right/left to see the hole page. Looking forward to your official new version. Thank you very much.

**Comment by thenoncoder** [comment]
I had suggested that there be an option to switch between the old and new designs, which is the best solution.
Users who prefer the new design can use it, and those who prefer the old design can use it too.
Problem solved.

**Comment by Quicksaver** [comment]
> If the sidebar is at left or right, it will impact the layout/appearance of the web page and users need to scroll right/left to see the whole page.

Precisely one of the biggest issues with the lists at the top or bottom. The trend is not for taller screens, but for wider screens. Right now, most webpages are optimized for that trend, by centering their content and leaving margins on the sides for those wider screens (look at this very own github page). They have a mostly fixed or adaptable width, whereas their height will almost always just go as large as the content needs it to be, almost always bigger than the screen. This has been the trend for years and will remain so for many more, so a sidebar will always better adapt to the web content because of this.

In other words, the lists at the top or bottom will always take over lots of web content space, to which the webpage will never adapt, you'll just see a thinner portion of the webpage. Plus these lists take up the whole width of the window unnecessarily, so for even very large monitors lots of that space is wasted. Lists on the sides have none of these drawbacks, with the added bonus that many webpages are made to adapt to smaller widths viewports, meaning that the horizontal scrollbars won't be a nuisance as often as you think.

(By the way, the lists also do that horizontal scrolling automatically, just as they scroll vertically when selecting a match from the lists. I'm assuming this is obvious though so I won't get into that point.)

> Such that, I can see both web page and "find in all tabs" and navigate them with up/down arrow key at the same time. Dobule-clicking or pressing enter are redundant operations compared with previous versions.

I agree, which is why the new lists are the very next feature I want to work on, and navigation between matches will function just as it did before.

> I had suggested that there be an option to switch between the old and new designs, which is the best solution.

And I explained not only why I don't agree with the lists on the top or the bottom as a design choice, but also why I can't have multiple modes like this. It's not that I'm opposed to giving you a choice (I would love to do that), but none of these are easy features to code, it is a large effort to maintain large features like these.

Since I'm the one who spends that time and effort, I'm the one who has to decide where to put it. The more options the add-on has, the more the other parts of the add-on suffer as my time will be divided by more and more features. I can't make such a sacrifice for features that bring little to no benefit, and so far you haven't convinced me that the top/bottom lists are worth it, especially not when compared to the sides lists.

**Comment by thenoncoder** [comment]
@Julian-Lin was trying to say that having the *find in all tabs* window as a sidebar, means you can't see webpages properly, and as a result, you cannot find text properly, and I think that he's absolutely right!

**Comment by jimmybod** [comment]
Please bring back the "Find in All Tabs" window without the need to click on "Find in All Tabs". The absolutely focus on this Extension was THAT feature. Type your search an see immediately in one window all hits in a small summary - This is a key feature what makes this addon so worth to use. Please bring it back :-)

**Comment by Quicksaver** [comment]
Whew, that took a while. Care to give beta version 2.1b2 a try? https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1b2

Also make sure to check out the new Find All pane in the preferences for some customization options already implemented.
