### ISSUE TITLE
Selected text cannot be unselected normally [ 2.02b1 ]

### ISSUE THREAD

**Issue by thenoncoder** [Quicksaver/FindBar-Tweak#208]
Usually, when I select text, clicking outside the selection unselects  it, but now, I have to click twice to unselect it! 
Only happens with large text, kinda h1 or h2 size.

**Comment by Quicksaver** [comment]
Text size shouldn't make a difference. Could you give me a specific example of where this is happening? Webpage, what text you selected, where are you clicking "outside" to unselect it, etc.

**Comment by thenoncoder** [comment]
Try it on the page of this issue itself.
Select the words `FindBar-Tweak` at the very top of the page. Then click outside the selection.
The normal thing is that now the text should be unselected, but what happens is that the selection turns purple, and then you have to click outside it again, to unselect it.
Then try selecting the text of any comment, when you click outside it, it does what it should do, that is, unlselect the text, but it still makes it turn purple for like a split-second!

**Comment by thenoncoder** [comment]
On pages where this doesn't happen, the selection colour turns to purple before the text unselects.

**Comment by Quicksaver** [comment]
You're right of course, that particular text at the top needs a second click outside of it to clear the findbar, although I admit I have no idea why that is different from anywhere else on the page...

Either way, beta version 2.0.2b2 should fix that. You can find it at https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.0.2b2 if you'd like to try it.

>  it unlselects the text, but it still makes it turn purple ( sometimes green too ) for a duration of some milliseconds.

That's unavoidable. That's because behind the text selection there's also a highlight. And since adding or removing the highlights is an asynchronous process, it sometimes can take a few milliseconds to finish so you end up seeing the highlight for a moment after you unselect text.
