### ISSUE TITLE
Breaks under heavy memory consumption

### ISSUE THREAD

**Issue by AufbeschissenerKunde** [Quicksaver/FindBar-Tweak#221]
Firefox 40.0.3, Windows 7 64-bit.

Maybe Firefox is to blame for this; if you don't think you can do anything about it, go ahead and close this ticket.

The issue I experienced is that Findbar would not search an HTML document with a lot of invalid HTML (specifically no document declaration, HTML without an HTML element).  I would type in a search word, press enter or click the "find next" arrow button, but FindBar indicated neither matches nor lack of matches.  It still worked on other HTML and plain text pages correctly, but not this one.

Also of note is the fact that Firefox was currently gorging itself on 1.1GB of RAM.  (I have found that Firefox starts breaking down and not behaving correctly when consuming around 1GB of RAM, requiring a restart, even after I upgraded my RAM from 4GB to 32GB.)  I restarted Firefox, and Finder started working correctly again, so like I said, Firefox might actually be at fault here.

**Comment by Quicksaver** [comment]
First of all, unfortunately upgrading your RAM won't do much for Firefox, at least until multiprocess Firefox (e10s) is released, which should happen by the end of the year (but could still be pushed back a little more). So yeah, when FIrefox consumes that much memory right now it will not behave very well.

Still, the way you describe it seems like another problem, it sounds like the findbar lost communication with its tab. Can you think of anything you may have done before on that specific tab that you might not have done in the others? Such as switching to a Firefox native panel like the add-ons manager or the preferences tab, and then switch again to a normal webpage? Or maybe some other add-on you have that might have acted on it? Anything like that?

**Comment by AufbeschissenerKunde** [comment]
All I can specifically recall about the event is that I switched to another tab to make sure FindBar wasn't 100% broken (it wasn't), then switched back to the one tab to try again, tried to force-refresh the page a few times, and somewhere in there I closed and re-opened the find bar, but to no avail.  (Sometimes when Firefox gets gorged like this, it won't even update a webpage's style cache no matter how many times I hammer on the force-refresh.)  I'm thinking this is probably just Firefox being Firefox, and I apologize for wasting your time.

**Comment by Quicksaver** [comment]
I meant if you remembered anything from **before** the findbar stopped working. But I don't expect you'd remember now after all this time of course. :)

If this happens again and you can remember anything specific that happened on that tab from **before** it stopped working, let me know. So far I have only come across one scenario where this would happen (switching from a webpage to the add-ons manager and then back to a webpage again), which I have already fixed, so this scenario is improbable to have caused the issue for you, but I'm mentioning it still doesn't work for you for some reason.

Whatever caused this issue for you should be rare enough that shouldn't interfere a lot with your browsing, but still it's very serious because after the findbar has lost communication with its tab there's no way to get it back, you'll have to close it and open another one if you want.

**Comment by AufbeschissenerKunde** [comment]
This hasn't happened again in recent memory, so I think we can consider the issue resolved.

**Comment by Quicksaver** [comment]
Great, thanks for letting me know.
