### ISSUE TITLE
Find in All Tabs - Multiple Windows

### ISSUE THREAD

**Issue by Luvechyle** [Quicksaver/FindBar-Tweak#225]
Using FF 41.0.1, FBT 2.1 - I cannot search across multiple windows. The FB only works if all tabs are located in the window where you activated the search.

If i want to search all tabs and I hit 'find in all tabs' the window detaches and opens a new window only then would the search include all tabs. Is this the intended way to use?

**Comment by Quicksaver** [comment]
I assume you mean the Find All sidebar. This is expected, the sidebar only searches tabs in its own window. To find in all open windows you need to use the Find in All Tabs standalone dialog as before; there's a button at the top of the sidebar to quickly open it when you need it, and of course you can configure the add-on to always open the Find in All Tabs instead of the Find All sidebar if you want in the add-on preferences.

If this is not what you meant, let me know.
