### ISSUE TITLE
Breaks Additional Toolbars

### ISSUE THREAD

**Issue by BarbieBarb** [Quicksaver/FindBar-Tweak#253]
I have two additional Toolbars from Firefox 28 that, although I cannot create any new Toolbars, the previous Additional Toolbars have carried over through to all future firefox versions.
However, Findbar Tweak (from Firefox 44+) has broken these Addional Toollbars, they disappear and all the extra buttons that were placed on them are moved into the Pallette.
I have so many buttons, and so I need the toolbars space to place them on. It is mandatory.
I've rolled back to Firefox 43.

Is it possible for Findbar Tweak to not break Additional Toolbars please?
Unless you know of a firefox addon that adds more Toolbars in later firefox versions that will not be blocked by FindbarTweak?
Please and Thankyou

#navigator-toolbox #customize-toolbar
#navigator-toolbox #__customToolbar_ExtraButtons
#navigator-toolbox #__customToolbar_BBCode

![firefox create new toolbar arrow](https://cloud.githubusercontent.com/assets/6320584/14303247/ba592db0-fb5d-11e5-8345-bde3d3600fef.png)

**Comment by Quicksaver** [comment]
Why do you believe FBT is getting rid of your toolbars? I have serious doubts it's FBT doing it, there's just no toolbar interaction in it at all. Especially between Firefox 43 and 44 which has absolutely no change in that area. I'm almost sure there is a conflict with another add-on there other than FBT. (I'm not disregarding your problem of course, I just don't believe FBT is the root cause here.)

Either way, there are other add-ons to create extra toolbars if that's all you need, [Puzzle Bars](https://addons.mozilla.org/firefox/addon/puzzle-toolbars/) or [Classic Theme Restorer](https://addons.mozilla.org/firefox/addon/classicthemerestorer/) are just two examples. There's really nothing I can do to support those toolbars from older versions, since they're not "supported" themselves anymore in Firefox. You'll have to use one of those add-ons to add more space for your buttons.
