### ISSUE TITLE
Enter closes QuickFindBar, no FindAll button

### ISSUE THREAD

**Issue by zetapulse** [Quicksaver/FindBar-Tweak#272]
Pressing Enter, instead of cycling through the found words, just closes QuickFindBar, as though the focus got set onto the text it highlighted in the webpage. I've set it to always use the normal FindBar & the issue doesn't bother me, nor do I see a difference between the  two variants, considering I've set QFB to show buttons as well.
I'm not personally seeking to make use of the FindAll button, but it's missing for me.

**Comment by Quicksaver** [comment]
First of all, I'm sorry it took me so long to respond.

It's supposed to do that, so that if you want to find some text in a link, you can use Enter to quickly follow that link. To scroll through the found matches, you can use F3 instead of Enter, or use the normal findbar instead of the quick findbar like you're already using.

**Comment by zetapulse** [comment]
No worries mate, I'm also sorry for having suddenly had the urge to report so many bugs I've been keeping quiet about in one go. I'll try to spread them out a bit next time :P
Thanks for the tip, I'll use (Shift+)F3 with quickfind from now on.
