### ISSUE TITLE
Scrollbar color issue

### ISSUE THREAD

**Issue by letrollpoilu** [Quicksaver/FindBar-Tweak#285]
I don't know why but the colour in the scrollbar is not working on this website:

http://www.clearskinforever.net/peanut-butter-acne/

**Comment by Quicksaver** [comment]
It seems to work for me. What are you searching for that doesn't appear in the scrollbar?

**Comment by letrollpoilu** [comment]
I'm looking for peanut

**Comment by Quicksaver** [comment]
"peanut" shows 120 matches for me. Remember the default limit for matches in the grid is 100, could that be why it's not showing for you? Try increasing the limit in your FBT's preferences and see if they appear then.

That limit exists because calculating the position of each match is heavy work. The more matches a page has, the slower a search becomes. If that is the case, maybe you can increase that limit safely in your machine, you'll have to see when it starts becoming to slow, each machine is different.

**Comment by letrollpoilu** [comment]
Oh yeah you are right... I'm deeply sorry that I've made you lost that time.. Indeed it was because of this limit, I didn't see it and thought it was a "bug" of the new beta.

Thanks a lot for helping me out and so quickly! Have a nice Sunday, and apologies for that again.

**Comment by Quicksaver** [comment]
It's no problem. Let me know if you ever run into any other issues. :)
