### ISSUE TITLE
Disqus comments highlights grid failure. 

### ISSUE THREAD

**Issue by mzso** [Quicksaver/FindBar-Tweak#93]
If I search on a website containing disqus comments I usuall get something like this:
![fb-high2](https://f.cloud.github.com/assets/4479090/1607169/c6aa2b84-5473-11e3-87fd-ba35a979b065.PNG)
![fb-high1](https://f.cloud.github.com/assets/4479090/1607170/c6ae781a-5473-11e3-8c19-b9684f69fb65.PNG)

The really long checkboard pattern highlight is particularly weird. But I also get some sort of grid in content, which more confusing than helpful.

**Comment by deant** [comment]
The title of this bug should really be "Highlight Grid doesn't work inside frames".  Otherwise someone will likely add a duplicate bug for the issue. (I was going to when I found this).

Because... the highlight grid doesn't work inside frames or iframes!
(It just highlights the entire area of the frame or iframe in the main window scrollbar).

Please fix that if possible!

**Comment by Quicksaver** [comment]
Actually the grid works just fine for me in iframes (at least with the latest beta https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b7). If with the beta you still have problems with grids in frames, open a new issue and link me to any webpage where you see the problem.

This issue is appropriately titled, the specific problem here is that the frame is shown as if it was part of the website itself. That's actually not very straightforward to detect, and sending those highlights to the main scrollbar has some complications, which I haven't had a chance to resolve yet.

**Comment by Quicksaver** [comment]
@mzso, I have to apologize, I completely overlooked the fact that fixing your issue became much easier than I had anticipated, because of the huge add-on rewrite that I did.

Everything seems to work for me now. Could you please try beta version v2b8 (https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b8) and let me know how it works for you?

There is one small issue I can see though, in that example you linked, if you for instance search for "ago" and keep hitting F3 to go through all the matches, when you're close to the bottom it will seem to "reset" the highlights, and it will start over at the top as soon as they're redone. This is because "something" in the webpage changes, usually AFAICT it's when it starts to load more comments to the bottom of the page.

I think it's the way the website works, it somehow reloads the iframe where these comments are to do this, which causes it to lose the cursor position so it starts from the top again. I'm not sure this is something that I can circumvent, as after this "reload" the highlights are physically different, so there's no (easy) way to know where to put the cursor back where it was before the reload.

Just let me know if this becomes too bothersome and I'll take another look.

**Comment by mzso** [comment]
Cool I'll check it out.

**Comment by mzso** [comment]
It seems to work great with the solidopiniong commenting system on nextbigfuture.

It seems to work the same with disqus as it did when I opened this issue.
eg: http://www.spoilertv.com/2015/04/movies-captain-america-civil-war-news.html

**Comment by Quicksaver** [comment]
Right you are, v2b10 should fix this. https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2b10

**Comment by mzso** [comment]
Excellent.
